package com.simple_developement.credit_card_originating_system;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Account Number")
	private long accountNumber;
	@org.kie.api.definition.type.Label(value = "Aadhar Id")
	private long aadharId;

	public Customer() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public long getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(long accountNumber) {
		this.accountNumber = accountNumber;
	}

	public long getAadharId() {
		return this.aadharId;
	}

	public void setAadharId(long aadharId) {
		this.aadharId = aadharId;
	}

	public Customer(java.lang.String name, long accountNumber, long aadharId) {
		this.name = name;
		this.accountNumber = accountNumber;
		this.aadharId = aadharId;
	}

}